# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fb42ec6662f46abb2bfa0a62582380822e2932a694eb16286e898f8715d36ae7aa59c80341715d120fac4a102b6c622669354ae8444976a4c39abb991616e60

test:
  secret_key_base: fcc48e30b3d1576e225db24dc9373c7f705ef4ee4762a7d5dcfc06202395eae2faa52cb779da5c646076e852a80a18e014bff1a859a429c6c5457416d81ae54b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
